In [1]:
import pickle
import numpy as np
ohe_sex = pickle.load(open('/content/drive/MyDrive/Colab Notebooks/Day 29/models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('/content/drive/MyDrive/Colab Notebooks/Day 29/models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('/content/drive/MyDrive/Colab Notebooks/Day 29/models/clf.pkl','rb'))

In [2]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [3]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))
test_input_sex

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 1.]])

In [4]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))
test_input_embarked

array([[0., 0., 1.]])

In [5]:
test_input_age = test_input[:,2].reshape(1,1)
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)
test_input_transformed.shape

(1, 10)

In [6]:
clf.predict(test_input_transformed)

ValueError: X has 10 features, but DecisionTreeClassifier is expecting 13 features as input.